In [1]:
import numpy as np

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
vector = np.arange(0,9)
lst = np.random.random((3,3))
print(lst)

[[0.29701326 0.66114022 0.79317107]
 [0.62530613 0.0369679  0.5263362 ]
 [0.90208405 0.89653546 0.30026371]]


In [10]:

new_lst = [1,2,0,0,4,0] 
lst = np.nonzero(new_lst)
lst

(array([0, 1, 4]),)

In [11]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
    
lst = np.random.random((3,3,3))
print(lst)

[[[0.22846288 0.45746305 0.12397928]
  [0.15117469 0.89414569 0.02997595]
  [0.94521482 0.63175948 0.71734376]]

 [[0.67024818 0.62974562 0.89402256]
  [0.30663836 0.99174446 0.98244595]
  [0.78904636 0.80710812 0.03352508]]

 [[0.2383553  0.80783892 0.01638641]
  [0.87029204 0.52197389 0.6990705 ]
  [0.53317018 0.46453013 0.07265825]]]


In [14]:
lst = np.random.random((10,10))
print(lst)

[[0.56057711 0.04516818 0.81277858 0.96879666 0.31440063 0.05033812
  0.07273288 0.30241378 0.69245815 0.30558833]
 [0.14402009 0.42843919 0.16429313 0.97771014 0.51682315 0.17074139
  0.56024216 0.35456245 0.79028832 0.91855815]
 [0.56086859 0.60491877 0.88263939 0.493668   0.74780035 0.48887593
  0.32344575 0.20447018 0.78321464 0.89325957]
 [0.29257866 0.24242034 0.26464166 0.29556167 0.03499607 0.75720589
  0.36952897 0.82901705 0.08500624 0.95664133]
 [0.94086086 0.86501433 0.71845052 0.77632695 0.28972507 0.10154733
  0.86305226 0.39779283 0.77706415 0.06942746]
 [0.99529167 0.51663054 0.65385502 0.72042988 0.69679213 0.22968009
  0.70019417 0.57312282 0.86577945 0.67249173]
 [0.48829619 0.54267275 0.98585995 0.14778796 0.36841972 0.33937969
  0.58798532 0.66979482 0.49065187 0.71952242]
 [0.37358991 0.7764336  0.99492785 0.07747235 0.50123091 0.31084009
  0.43947032 0.36290345 0.04751861 0.09487904]
 [0.78279084 0.84636507 0.84279411 0.35975494 0.67423167 0.25376771
  0.61880783

In [18]:
min_value = np.min(lst)
max_value = np.max(lst)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.034996070054720274
Maximum value: 0.99529167260478
